// <auto-generated />
namespace structure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class userId_to_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userId_to_int));
        
        string IMigrationMetadata.Id
        {
            get { return "201402091914206_userId_to_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
